SET DATABASE SQL SYNTAX MYS TRUE;

drop table t_role if exists;
create table t_role
(
    id        bigint generated by default as identity (start with 1) primary key,
    role_name VARCHAR(100) not null,
    valid     boolean DEFAULT TRUE
);

drop table t_user if exists;
create table t_user
(
    id       bigint generated by default as identity (start with 1) primary key,
    username VARCHAR(100) not null,
    email    VARCHAR(100) not null,
    valid    boolean DEFAULT TRUE
);


create table a_user_and_role (user_id bigint, role_id int);

create table a_role_and_perm (role_id int, perm_id int);

create table t_perm
(
    id        bigint generated by default as identity (start with 1) primary key,
    perm_name VARCHAR(100) not null,
    valid     boolean DEFAULT TRUE
);


INSERT INTO t_user (username, email, valid) VALUES ('admin-1', 'aaa@qq.com', true);
INSERT INTO t_user (username, email, valid) VALUES ('dev-1', 'bbb@qq.com', true);
INSERT INTO t_user (username, email, valid) VALUES ('dev-2', 'ccc@qq.com', true);

INSERT INTO t_role (role_name, valid) VALUES ('admin', true);
INSERT INTO t_role (role_name, valid) VALUES ('vip', true);
INSERT INTO t_role (role_name, valid) VALUES ('vip2', true);
INSERT INTO t_role (role_name, valid) VALUES ('vip3', true);
INSERT INTO t_role (role_name, valid) VALUES ('guest', true);

INSERT INTO t_perm (perm_name, valid) VALUES ('user:list', true);
INSERT INTO t_perm (perm_name, valid) VALUES ('user:new', true);
INSERT INTO t_perm (perm_name, valid) VALUES ('user:edit', true);
INSERT INTO t_perm (perm_name, valid) VALUES ('user:delete', true);

INSERT INTO a_user_and_role (user_id, role_id) VALUES (1, 1);
INSERT INTO a_user_and_role (user_id, role_id) VALUES (2, 2);

INSERT INTO a_role_and_perm (role_id, perm_id) VALUES (1, 1);
INSERT INTO a_role_and_perm (role_id, perm_id) VALUES (1, 2);
INSERT INTO a_role_and_perm (role_id, perm_id) VALUES (1, 3);
INSERT INTO a_role_and_perm (role_id, perm_id) VALUES (1, 4);
INSERT INTO a_role_and_perm (role_id, perm_id) VALUES (2, 1);

